name: Publish

on:
  workflow_dispatch:

jobs:
  cargo-publish:
    runs-on: rust-latest-amd64

    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y curl gcc git-lfs nodejs
      - uses: actions/checkout@v4
      - name: Checkout LFS objects
        run: git lfs pull
      - name: Login into crates.io
        run: cargo login ${{ secrets.CRATES_IO }}
      - name: Publish to crates.io
        run: cargo publish
